apiVersion: v1
data:
  VUE_APP_URL: "http://3.83.178.135:31784/"

kind: ConfigMap
metadata:
  name: service-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: POSShop
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: POSShop
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: michan11/vue-jenkins:master
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-frontend
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: POSShop
    tier: frontend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: frontendport
